// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ5JEgRaTGEwBsorrtm8DjwDnmzCIFUqY',
    appId: '1:463349550398:web:83e9096e441b0a3d43306f',
    messagingSenderId: '463349550398',
    projectId: 'piyawat-d038f',
    authDomain: 'piyawat-d038f.firebaseapp.com',
    storageBucket: 'piyawat-d038f.firebasestorage.app',
    measurementId: 'G-2L9Y83FH1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvVoTKjoNu7VaMrdRuYttPYAlQCCrdi9Y',
    appId: '1:463349550398:android:1db4a809ce77133743306f',
    messagingSenderId: '463349550398',
    projectId: 'piyawat-d038f',
    storageBucket: 'piyawat-d038f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM0UnWMJaaeXu3Gq_XnembnhW9dkGTmIQ',
    appId: '1:463349550398:ios:b0d5f10f81a0ab1a43306f',
    messagingSenderId: '463349550398',
    projectId: 'piyawat-d038f',
    storageBucket: 'piyawat-d038f.firebasestorage.app',
    iosBundleId: 'com.example.newPiyawat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM0UnWMJaaeXu3Gq_XnembnhW9dkGTmIQ',
    appId: '1:463349550398:ios:b0d5f10f81a0ab1a43306f',
    messagingSenderId: '463349550398',
    projectId: 'piyawat-d038f',
    storageBucket: 'piyawat-d038f.firebasestorage.app',
    iosBundleId: 'com.example.newPiyawat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ5JEgRaTGEwBsorrtm8DjwDnmzCIFUqY',
    appId: '1:463349550398:web:f05f57932264b6a843306f',
    messagingSenderId: '463349550398',
    projectId: 'piyawat-d038f',
    authDomain: 'piyawat-d038f.firebaseapp.com',
    storageBucket: 'piyawat-d038f.firebasestorage.app',
    measurementId: 'G-1SN86DDJRN',
  );
}
